import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Aurora: a slowly drifting gradient mesh behind frosted glass cards. */
export const theme: ThemeDef = {
  id: 'aurora',
  name: 'Aurora',
  tagline: 'Northern lights and frosted glass',
  defaultMode: 'dark',
  fonts: {
    body: stack('inter', SANS_FALLBACK),
    heading: stack('sora', SANS_FALLBACK),
    mono: stack('jetbrains', MONO_FALLBACK),
  },
  fontKeys: ['inter', 'sora', 'jetbrains'],
  baseSize: 17,
  lineHeight: 1.7,
  radius: '16px',
  measure: 860,
  css: () => import('../css/aurora.css?inline').then((m) => m.default),
  card: { background: 'mesh' },
  variants: {
    dark: {
      bg: '#070713',
      bgAlt: '#0e0f24',
      surface: '#12132b',
      text: '#e6e7fb',
      muted: '#a6a9d4',
      heading: '#ffffff',
      accent: '#a78bfa',
      accentText: '#0b0718',
      link: '#8fd6ff',
      border: '#2a2b55',
      codeBg: '#0b0c1e',
      codeText: '#e2e4ff',
      inlineCodeBg: '#1d1e3d',
      inlineCodeText: '#f5b8fd',
      mark: '#3f2c78',
      markText: '#ffffff',
      selection: '#a78bfa55',
      note: '#8fd6ff',
      tip: '#6ee7b7',
      important: '#c4b5fd',
      warning: '#fcd34d',
      caution: '#fda4af',
      syntax: {
        keyword: '#f0abfc',
        string: '#86efac',
        number: '#fdba74',
        comment: '#8f93c9',
        function: '#7dd3fc',
        type: '#fcd34d',
        variable: '#e2e4ff',
        attr: '#a5b4fc',
        tag: '#f9a8d4',
        punctuation: '#c7c9ee',
        meta: '#67e8f9',
        addition: '#86efac',
        deletion: '#fda4af',
      },
    },
    light: {
      bg: '#f6f6ff',
      bgAlt: '#eceeff',
      surface: '#ffffff',
      text: '#1b1b3a',
      muted: '#51537f',
      heading: '#120f36',
      accent: '#7c3aed',
      accentText: '#ffffff',
      link: '#6425d0',
      border: '#d9daf3',
      codeBg: '#15142e',
      codeText: '#e2e4ff',
      inlineCodeBg: '#efeaff',
      inlineCodeText: '#5b21b6',
      mark: '#e9d5ff',
      markText: '#1b1b3a',
      selection: '#c4b5fd88',
      note: '#1d4ed8',
      tip: '#047857',
      important: '#6d28d9',
      warning: '#92400e',
      caution: '#be123c',
      syntax: {
        keyword: '#f0abfc',
        string: '#86efac',
        number: '#fdba74',
        comment: '#9195cc',
        function: '#7dd3fc',
        type: '#fcd34d',
        variable: '#e2e4ff',
        attr: '#a5b4fc',
        tag: '#f9a8d4',
        punctuation: '#c7c9ee',
        meta: '#67e8f9',
        addition: '#86efac',
        deletion: '#fda4af',
      },
    },
  },
};
