import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Blueprint: a technical drawing with a gridded sheet, title block, callouts and dimension lines. */
export const theme: ThemeDef = {
  id: 'blueprint',
  name: 'Blueprint',
  tagline: 'Technical drawing, sheet 1 of 1',
  defaultMode: 'dark',
  fonts: {
    body: stack('plexSans', SANS_FALLBACK),
    heading: stack('spaceGrotesk', SANS_FALLBACK),
    mono: stack('plexMono', MONO_FALLBACK),
  },
  fontKeys: ['spaceGrotesk', 'plexSans', 'plexMono'],
  baseSize: 16,
  lineHeight: 1.7,
  radius: '0px',
  measure: 820,
  css: () => import('../css/blueprint.css?inline').then((m) => m.default),
  card: { background: 'grid', titleCase: 'upper' },
  variants: {
    dark: {
      bg: '#0b3a86',
      bgAlt: '#0f4396',
      surface: '#10479c',
      text: '#f2f7ff',
      muted: '#b4cbf2',
      heading: '#ffffff',
      accent: '#7fe3ff',
      accentText: '#07224f',
      link: '#a6ecff',
      border: '#4d7cc7',
      codeBg: '#082c6a',
      codeText: '#eaf2ff',
      inlineCodeBg: '#08306f',
      inlineCodeText: '#ffe08a',
      mark: '#ffd166',
      markText: '#07224f',
      selection: '#7fe3ff55',
      note: '#a6ecff',
      tip: '#b8f5a0',
      important: '#d4b8ff',
      warning: '#ffd166',
      caution: '#ffb4a2',
      syntax: {
        keyword: '#7fe3ff',
        string: '#b8f5a0',
        number: '#ffd166',
        comment: '#95b3e6',
        function: '#ffffff',
        type: '#ffb4a2',
        variable: '#dce8ff',
        attr: '#a8d8ff',
        tag: '#7fe3ff',
        punctuation: '#b8cef5',
        meta: '#d4b8ff',
        addition: '#b8f5a0',
        deletion: '#ffb4a2',
      },
    },
    light: {
      bg: '#f4f6fa',
      bgAlt: '#e8eef8',
      surface: '#eef2f9',
      text: '#102a5c',
      muted: '#4a6190',
      heading: '#0b3a86',
      accent: '#1f5fd1',
      accentText: '#ffffff',
      link: '#1a4fb0',
      border: '#9fb4dc',
      codeBg: '#0b3a86',
      codeText: '#f2f7ff',
      inlineCodeBg: '#e2e9f6',
      inlineCodeText: '#0b3a86',
      mark: '#ffe08a',
      markText: '#102a5c',
      selection: '#1f5fd133',
      note: '#1a4fb0',
      tip: '#1d6b3a',
      important: '#5b3aa8',
      warning: '#8a5a00',
      caution: '#b3261e',
      syntax: {
        keyword: '#7fe3ff',
        string: '#b8f5a0',
        number: '#ffd166',
        comment: '#a3bdea',
        function: '#ffffff',
        type: '#ffb4a2',
        variable: '#dce8ff',
        attr: '#a8d8ff',
        tag: '#7fe3ff',
        punctuation: '#b8cef5',
        meta: '#d4b8ff',
        addition: '#b8f5a0',
        deletion: '#ffb4a2',
      },
    },
  },
};
