import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

const SYNTAX = {
  keyword: '#ff90e8',
  string: '#00d67a',
  number: '#ffb347',
  comment: '#9c9c9c',
  function: '#7cc4ff',
  type: '#ffe500',
  variable: '#f5f5f0',
  attr: '#c3aaff',
  tag: '#ff90e8',
  punctuation: '#d0d0d0',
  meta: '#5ce1e6',
  addition: '#00d67a',
  deletion: '#ff7070',
};

/** Neo-Brutalist: raw colour, thick black ink and hard offset shadows. */
export const theme: ThemeDef = {
  id: 'brutalist',
  name: 'Neo-Brutalist',
  tagline: 'Raw colour, thick ink, hard shadows',
  defaultMode: 'light',
  fonts: {
    body: stack('workSans', SANS_FALLBACK),
    heading: stack('archivoBlack', SANS_FALLBACK),
    mono: stack('spaceMono', MONO_FALLBACK),
  },
  fontKeys: ['workSans', 'archivoBlack', 'spaceMono'],
  baseSize: 17,
  lineHeight: 1.65,
  radius: '0px',
  measure: 820,
  css: () => import('../css/brutalist.css?inline').then((m) => m.default),
  card: { background: 'blocks', titleCase: 'upper' },
  variants: {
    light: {
      bg: '#fffdf5',
      bgAlt: '#fff3b8',
      surface: '#ffffff',
      text: '#0a0a0a',
      muted: '#4b4b4b',
      heading: '#000000',
      accent: '#ffe500',
      accentText: '#000000',
      link: '#1447e6',
      border: '#000000',
      codeBg: '#111111',
      codeText: '#f5f5f0',
      inlineCodeBg: '#ff90e8',
      inlineCodeText: '#000000',
      mark: '#ffe500',
      markText: '#000000',
      selection: '#ff90e8',
      note: '#1447e6',
      tip: '#00733f',
      important: '#7b2fd6',
      warning: '#9a5200',
      caution: '#d1001f',
      syntax: SYNTAX,
    },
    dark: {
      bg: '#0e0e0e',
      bgAlt: '#1c1c1c',
      surface: '#161616',
      text: '#f7f7f2',
      muted: '#b8b8b0',
      heading: '#ffffff',
      accent: '#ffe500',
      accentText: '#000000',
      link: '#7fb2ff',
      border: '#ffffff',
      codeBg: '#1b1b1b',
      codeText: '#f5f5f0',
      inlineCodeBg: '#ff90e8',
      inlineCodeText: '#000000',
      mark: '#ffe500',
      markText: '#000000',
      selection: '#ff90e8aa',
      note: '#7fb2ff',
      tip: '#3ee89a',
      important: '#c9a6ff',
      warning: '#ffc14d',
      caution: '#ff7a7a',
      syntax: SYNTAX,
    },
  },
};
