import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Comic: halftone paper, thick ink panels, speech bubbles and a lot of POW. */
export const theme: ThemeDef = {
  id: 'comic',
  name: 'Comic Book',
  tagline: 'Kapow! Your README, in ink',
  defaultMode: 'light',
  fonts: {
    body: stack('comicNeue', SANS_FALLBACK),
    heading: stack('bangers', SANS_FALLBACK),
    mono: stack('spaceMono', MONO_FALLBACK),
  },
  fontKeys: ['comicNeue', 'bangers', 'spaceMono'],
  baseSize: 18,
  lineHeight: 1.62,
  radius: '6px',
  measure: 800,
  css: () => import('../css/comic.css?inline').then((m) => m.default),
  card: { background: 'halftone', titleCase: 'upper' },
  variants: {
    light: {
      bg: '#fff8e7',
      bgAlt: '#fff0b8',
      surface: '#ffffff',
      text: '#111111',
      muted: '#4a4a4a',
      heading: '#111111',
      accent: '#d92b24',
      accentText: '#ffffff',
      link: '#1a5fb8',
      border: '#111111',
      codeBg: '#fffdf6',
      codeText: '#111111',
      inlineCodeBg: '#fff0a8',
      inlineCodeText: '#111111',
      mark: '#ffd400',
      markText: '#111111',
      selection: '#ffd40088',
      note: '#1a5fb8',
      tip: '#1f7a1f',
      important: '#7a3fc0',
      warning: '#955300',
      caution: '#c4161c',
      syntax: {
        keyword: '#c4161c',
        string: '#1f7a1f',
        number: '#7a3fc0',
        comment: '#6b6b6b',
        function: '#1a5fb8',
        type: '#9c4a00',
        variable: '#111111',
        attr: '#8a4b00',
        tag: '#c4161c',
        punctuation: '#444444',
        meta: '#0f6f73',
        addition: '#1f7a1f',
        deletion: '#c4161c',
      },
    },
  },
};
