import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SERIF_FALLBACK, stack } from '../fonts';

/** Editorial: a luxury magazine long-read. Fraunces display, Source Serif text, oxblood ink on warm paper. */
export const theme: ThemeDef = {
  id: 'editorial',
  name: 'Editorial',
  tagline: 'The long-read, beautifully typeset',
  defaultMode: 'light',
  fonts: {
    body: stack('sourceSerif', SERIF_FALLBACK, 'serif'),
    heading: stack('fraunces', SERIF_FALLBACK, 'serif'),
    mono: stack('plexMono', MONO_FALLBACK),
  },
  fontKeys: ['fraunces', 'sourceSerif', 'plexMono'],
  baseSize: 19,
  lineHeight: 1.72,
  radius: '2px',
  measure: 720,
  css: () => import('../css/editorial.css?inline').then((m) => m.default),
  card: { background: 'paper' },
  variants: {
    light: {
      bg: '#fbf8f3',
      bgAlt: '#f3ede3',
      surface: '#fffdf9',
      text: '#1c1917',
      muted: '#6b6259',
      heading: '#14110f',
      accent: '#9b1c1c',
      accentText: '#ffffff',
      link: '#9b1c1c',
      border: '#e2d9cc',
      codeBg: '#f4eee4',
      codeText: '#2a2420',
      inlineCodeBg: '#f1e8db',
      inlineCodeText: '#7a1d14',
      mark: '#f6e3a8',
      markText: '#1c1917',
      selection: '#9b1c1c2e',
      note: '#1e4e8c',
      tip: '#2f6b2f',
      important: '#6b2c91',
      warning: '#8a5a00',
      caution: '#9b1c1c',
      syntax: {
        keyword: '#9b1c1c',
        string: '#3f6212',
        number: '#9a4a0a',
        comment: '#7d7266',
        function: '#1e3a8a',
        type: '#854d0e',
        variable: '#2a2420',
        attr: '#5b3a8c',
        tag: '#9b1c1c',
        punctuation: '#57514a',
        meta: '#6b6259',
        addition: '#3f6212',
        deletion: '#9b1c1c',
      },
    },
    dark: {
      bg: '#1a1714',
      bgAlt: '#221e1a',
      surface: '#24201c',
      text: '#ece4d6',
      muted: '#b3a899',
      heading: '#f7f0e3',
      accent: '#e4826b',
      accentText: '#1a1714',
      link: '#eb9580',
      border: '#3a332c',
      codeBg: '#211d19',
      codeText: '#e6dccb',
      inlineCodeBg: '#2d2722',
      inlineCodeText: '#f2b8a6',
      mark: '#5a4414',
      markText: '#fff3d6',
      selection: '#e4826b40',
      note: '#8fb8e8',
      tip: '#9dcf8f',
      important: '#c9a8e0',
      warning: '#e8b86a',
      caution: '#f08c74',
      syntax: {
        keyword: '#f08c74',
        string: '#b5c98a',
        number: '#e8b36a',
        comment: '#948978',
        function: '#9cc0e8',
        type: '#e6c07b',
        variable: '#e6dccb',
        attr: '#c9a8e0',
        tag: '#f08c74',
        punctuation: '#b3a899',
        meta: '#c7b9a5',
        addition: '#b5c98a',
        deletion: '#f08c74',
      },
    },
  },
};
