import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Frost: crisp glassmorphism on an icy winter sky. */
export const theme: ThemeDef = {
  id: 'frost',
  name: 'Frost',
  tagline: 'Icy glass on a winter sky',
  defaultMode: 'light',
  fonts: {
    body: stack('jakarta', SANS_FALLBACK),
    heading: stack('jakarta', SANS_FALLBACK),
    mono: stack('jetbrains', MONO_FALLBACK),
  },
  fontKeys: ['jakarta', 'jetbrains'],
  baseSize: 17,
  lineHeight: 1.72,
  radius: '14px',
  measure: 820,
  css: () => import('../css/frost.css?inline').then((m) => m.default),
  card: { background: 'frost' },
  variants: {
    light: {
      bg: '#eef4fb',
      bgAlt: '#e2ebf6',
      surface: '#f8fbff',
      text: '#1e2a3b',
      muted: '#4c5a70',
      heading: '#0f1b2d',
      accent: '#1d6fe0',
      accentText: '#ffffff',
      link: '#1a62c9',
      border: '#cbdaec',
      codeBg: '#1b2638',
      codeText: '#e3ecf8',
      inlineCodeBg: '#e0eafa',
      inlineCodeText: '#174fa6',
      mark: '#cfe2ff',
      markText: '#0f1b2d',
      selection: '#1d6fe033',
      note: '#1a62c9',
      tip: '#0d7355',
      important: '#6a3fd1',
      warning: '#85570a',
      caution: '#bf2f49',
      syntax: {
        keyword: '#93b8ff',
        string: '#9fe6c9',
        number: '#ffc690',
        comment: '#8795ae',
        function: '#7fd3ff',
        type: '#d6bcff',
        variable: '#e3ecf8',
        attr: '#a9c9ff',
        tag: '#ffa3bb',
        punctuation: '#b9c5d8',
        meta: '#7fe0e6',
        addition: '#9fe6c9',
        deletion: '#ffa3b1',
      },
    },
    dark: {
      bg: '#0b1220',
      bgAlt: '#111a2c',
      surface: '#131d31',
      text: '#e3ecf7',
      muted: '#9eb0c8',
      heading: '#f4f8ff',
      accent: '#5fd3f3',
      accentText: '#06101c',
      link: '#7fdcf7',
      border: '#26344d',
      codeBg: '#070d18',
      codeText: '#dfe8f5',
      inlineCodeBg: '#172540',
      inlineCodeText: '#9fe3f7',
      mark: '#1d4a63',
      markText: '#f4f8ff',
      selection: '#5fd3f344',
      note: '#82b8ff',
      tip: '#6fe0b5',
      important: '#c3a8ff',
      warning: '#f5c56b',
      caution: '#ff91a4',
      syntax: {
        keyword: '#93b8ff',
        string: '#9fe6c9',
        number: '#ffc690',
        comment: '#7788a6',
        function: '#7fdcf7',
        type: '#d6bcff',
        variable: '#dfe8f5',
        attr: '#a9c9ff',
        tag: '#ffa3bb',
        punctuation: '#aab7cb',
        meta: '#7fe0e6',
        addition: '#9fe6c9',
        deletion: '#ffa3b1',
      },
    },
  },
};
