import type { ThemeDef } from '../types';
import { MONO_FALLBACK } from '../fonts';

const SYSTEM = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, 'Noto Sans Arabic Variable', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'";

/** GitHub Classic: a faithful baseline, the way a README looks on github.com. */
export const theme: ThemeDef = {
  id: 'github',
  name: 'GitHub Classic',
  tagline: 'The familiar look, done right',
  defaultMode: 'light',
  fonts: { body: SYSTEM, heading: SYSTEM, mono: MONO_FALLBACK },
  fontKeys: [],
  baseSize: 16,
  lineHeight: 1.6,
  radius: '6px',
  measure: 880,
  css: () => import('../css/github.css?inline').then((m) => m.default),
  card: { background: 'plain' },
  variants: {
    light: {
      bg: '#ffffff',
      bgAlt: '#f6f8fa',
      surface: '#f6f8fa',
      text: '#1f2328',
      muted: '#59636e',
      heading: '#1f2328',
      accent: '#0969da',
      accentText: '#ffffff',
      link: '#0969da',
      border: '#d1d9e0',
      codeBg: '#f6f8fa',
      codeText: '#1f2328',
      inlineCodeBg: '#eff1f3',
      inlineCodeText: '#1f2328',
      mark: '#fff8c5',
      markText: '#1f2328',
      selection: '#b6e3ff',
      note: '#0969da',
      tip: '#1a7f37',
      important: '#8250df',
      warning: '#9a6700',
      caution: '#d1242f',
      syntax: {
        keyword: '#cf222e',
        string: '#0a3069',
        number: '#0550ae',
        comment: '#59636e',
        function: '#6639ba',
        type: '#953800',
        variable: '#953800',
        attr: '#0550ae',
        tag: '#116329',
        punctuation: '#1f2328',
        meta: '#0550ae',
        addition: '#116329',
        deletion: '#82071e',
      },
    },
    dark: {
      bg: '#0d1117',
      bgAlt: '#151b23',
      surface: '#151b23',
      text: '#f0f6fc',
      muted: '#9198a1',
      heading: '#f0f6fc',
      accent: '#4493f8',
      accentText: '#0d1117',
      link: '#4493f8',
      border: '#3d444d',
      codeBg: '#151b23',
      codeText: '#f0f6fc',
      inlineCodeBg: '#262c36',
      inlineCodeText: '#f0f6fc',
      mark: '#4d3b10',
      markText: '#f0f6fc',
      selection: '#1f6feb66',
      note: '#4493f8',
      tip: '#3fb950',
      important: '#ab7df8',
      warning: '#d29922',
      caution: '#f85149',
      syntax: {
        keyword: '#ff7b72',
        string: '#a5d6ff',
        number: '#79c0ff',
        comment: '#9198a1',
        function: '#d2a8ff',
        type: '#ffa657',
        variable: '#ffa657',
        attr: '#79c0ff',
        tag: '#7ee787',
        punctuation: '#f0f6fc',
        meta: '#79c0ff',
        addition: '#aff5b4',
        deletion: '#ffdcd7',
      },
    },
  },
};
