import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SERIF_FALLBACK, stack } from '../fonts';

/** Manuscript: an illuminated page of parchment, iron-gall ink, rubrics and gold leaf. */
export const theme: ThemeDef = {
  id: 'manuscript',
  name: 'Manuscript',
  tagline: 'Rubrics, gold leaf and vellum',
  defaultMode: 'light',
  fonts: {
    body: stack('ebGaramond', SERIF_FALLBACK, 'serif'),
    heading: stack('cinzel', SERIF_FALLBACK, 'serif'),
    mono: stack('plexMono', MONO_FALLBACK),
  },
  fontKeys: ['ebGaramond', 'cinzel', 'cinzelDeco', 'plexMono'],
  baseSize: 20,
  lineHeight: 1.66,
  radius: '2px',
  measure: 720,
  css: () => import('../css/manuscript.css?inline').then((m) => m.default),
  card: { background: 'parchment', titleCase: 'upper' },
  variants: {
    light: {
      bg: '#f4e9cf',
      bgAlt: '#ecdcb6',
      surface: '#f8efd9',
      text: '#2b1d12',
      muted: '#5c4733',
      heading: '#2e1c10',
      accent: '#8f1d1d',
      accentText: '#fbf2dc',
      link: '#8a1c1c',
      border: '#c8ae84',
      codeBg: '#efe2c3',
      codeText: '#2b1d12',
      inlineCodeBg: '#ead8b0',
      inlineCodeText: '#6b1515',
      mark: '#f0d48a',
      markText: '#2b1d12',
      selection: '#b8860b55',
      note: '#1f3f73',
      tip: '#2d5a37',
      important: '#5a2d7a',
      warning: '#744508',
      caution: '#8f1d1d',
      syntax: {
        keyword: '#8f1d1d',
        string: '#2d5a37',
        number: '#784511',
        comment: '#77634d',
        function: '#1f3f73',
        type: '#653683',
        variable: '#2b1d12',
        attr: '#70430e',
        tag: '#8f1d1d',
        punctuation: '#57432f',
        meta: '#1d5550',
        addition: '#2d5a37',
        deletion: '#8f1d1d',
      },
    },
  },
};
