import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, SERIF_FALLBACK, stack } from '../fonts';

/** Midnight: an elegant night sky, ivory type and fine gold hairlines. */
export const theme: ThemeDef = {
  id: 'midnight',
  name: 'Midnight',
  tagline: 'Starlight, ivory and quiet gold',
  defaultMode: 'dark',
  fonts: {
    body: stack('manrope', SANS_FALLBACK),
    heading: stack('cormorant', SERIF_FALLBACK, 'serif'),
    mono: stack('jetbrains', MONO_FALLBACK),
  },
  fontKeys: ['manrope', 'cormorant', 'jetbrains'],
  baseSize: 17,
  lineHeight: 1.78,
  radius: '12px',
  measure: 760,
  css: () => import('../css/midnight.css?inline').then((m) => m.default),
  card: { background: 'stars' },
  variants: {
    dark: {
      bg: '#0a0f24',
      bgAlt: '#10173a',
      surface: '#121a3b',
      text: '#ebe5d5',
      muted: '#a7a6c2',
      heading: '#f7f0de',
      accent: '#e3c07a',
      accentText: '#0a0f24',
      link: '#ebca8a',
      border: '#2a335c',
      codeBg: '#070b1c',
      codeText: '#e6e1d3',
      inlineCodeBg: '#18204a',
      inlineCodeText: '#f1d69f',
      mark: '#4a3d20',
      markText: '#fff5de',
      selection: '#e3c07a47',
      note: '#a3b8ff',
      tip: '#8fd9b6',
      important: '#cbb6ff',
      warning: '#f1c776',
      caution: '#ffa3a3',
      syntax: {
        keyword: '#c9aaff',
        string: '#e3c07a',
        number: '#f6b48f',
        comment: '#7b84ab',
        function: '#93c3ff',
        type: '#9fdcc2',
        variable: '#e6e1d3',
        attr: '#b3c2f5',
        tag: '#f3a9c4',
        punctuation: '#aeb0cc',
        meta: '#9ed6e8',
        addition: '#a7e3b9',
        deletion: '#ffa3a3',
      },
    },
  },
};
