import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

const HAND_FALLBACK = "'Segoe Print', 'Bradley Hand', 'Comic Sans MS', cursive";

/** Notebook: handwritten notes on cream lined paper, or chalk on a green board in dark mode. */
export const theme: ThemeDef = {
  id: 'notebook',
  name: 'Notebook',
  tagline: 'Handwritten notes on lined paper',
  defaultMode: 'light',
  fonts: {
    body: stack('nunito', SANS_FALLBACK),
    heading: stack('caveat', HAND_FALLBACK),
    mono: stack('firaCode', MONO_FALLBACK),
  },
  fontKeys: ['caveat', 'nunito', 'firaCode'],
  baseSize: 17,
  lineHeight: 1.75,
  radius: '4px',
  measure: 780,
  css: () => import('../css/notebook.css?inline').then((m) => m.default),
  card: { background: 'lines' },
  variants: {
    light: {
      bg: '#fdf9ee',
      bgAlt: '#f6efdc',
      surface: '#fffdf6',
      text: '#1f2a44',
      muted: '#5b6378',
      heading: '#1d3fa6',
      accent: '#c8352c',
      accentText: '#ffffff',
      link: '#1d4fd6',
      border: '#d9cfb4',
      codeBg: '#fffef9',
      codeText: '#1f2a44',
      inlineCodeBg: '#f1ead6',
      inlineCodeText: '#9c2a22',
      mark: '#fff176',
      markText: '#1f2a44',
      selection: '#ffe95c99',
      note: '#1d4fd6',
      tip: '#2f7d32',
      important: '#7b3fa0',
      warning: '#9a5b00',
      caution: '#c8352c',
      syntax: {
        keyword: '#c8352c',
        string: '#2f7d32',
        number: '#b3541e',
        comment: '#7a7f8f',
        function: '#1d4fd6',
        type: '#7b3fa0',
        variable: '#1f2a44',
        attr: '#9a5b00',
        tag: '#c8352c',
        punctuation: '#4a5068',
        meta: '#5b6378',
        addition: '#2f7d32',
        deletion: '#c8352c',
      },
    },
    dark: {
      bg: '#1e2a24',
      bgAlt: '#25332c',
      surface: '#28372f',
      text: '#eef0e8',
      muted: '#b5c0b5',
      heading: '#f7e9a0',
      accent: '#ff9fb0',
      accentText: '#1e2a24',
      link: '#9fd8ff',
      border: '#4a5a50',
      codeBg: '#17211c',
      codeText: '#e8ecdf',
      inlineCodeBg: '#2c3b33',
      inlineCodeText: '#f7e9a0',
      mark: '#f7e9a0',
      markText: '#1e2a24',
      selection: '#f7e9a055',
      note: '#9fd8ff',
      tip: '#b8e986',
      important: '#c9b3ff',
      warning: '#ffd08a',
      caution: '#ff9fb0',
      syntax: {
        keyword: '#ff9fb0',
        string: '#b8e986',
        number: '#ffd08a',
        comment: '#8fa396',
        function: '#9fd8ff',
        type: '#f7e9a0',
        variable: '#e8ecdf',
        attr: '#c9b3ff',
        tag: '#ff9fb0',
        punctuation: '#b5c0b5',
        meta: '#9fe0d0',
        addition: '#b8e986',
        deletion: '#ff9f9f',
      },
    },
  },
};
