import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Pixel Arcade: 8-bit neon on an indigo night, or a Game Boy screen in light mode. */
export const theme: ThemeDef = {
  id: 'pixel',
  name: 'Pixel Arcade',
  tagline: 'Insert coin: an 8-bit arcade page',
  defaultMode: 'dark',
  fonts: {
    body: stack('pixelify', SANS_FALLBACK),
    heading: stack('pressStart', MONO_FALLBACK),
    mono: stack('vt323', MONO_FALLBACK),
  },
  fontKeys: ['pressStart', 'pixelify', 'vt323'],
  baseSize: 18,
  lineHeight: 1.6,
  radius: '0px',
  measure: 840,
  css: () => import('../css/pixel.css?inline').then((m) => m.default),
  card: { background: 'pixels', titleCase: 'upper' },
  variants: {
    dark: {
      bg: '#1b1433',
      bgAlt: '#231a42',
      surface: '#261d4a',
      text: '#efeaff',
      muted: '#b3a8e0',
      heading: '#ffd23f',
      accent: '#ff4f9a',
      accentText: '#1b1433',
      link: '#3de0ff',
      border: '#4a3b85',
      codeBg: '#120d24',
      codeText: '#efeaff',
      inlineCodeBg: '#2e2356',
      inlineCodeText: '#5cff7a',
      mark: '#ffd23f',
      markText: '#1b1433',
      selection: '#ff4f9a66',
      note: '#3de0ff',
      tip: '#5cff7a',
      important: '#c89bff',
      warning: '#ffd23f',
      caution: '#ff6b8b',
      syntax: {
        keyword: '#ff4f9a',
        string: '#5cff7a',
        number: '#ffd23f',
        comment: '#8a7fc0',
        function: '#3de0ff',
        type: '#ffa94d',
        variable: '#efeaff',
        attr: '#c89bff',
        tag: '#ff4f9a',
        punctuation: '#b3a8e0',
        meta: '#7af0e0',
        addition: '#5cff7a',
        deletion: '#ff6b6b',
      },
    },
    light: {
      bg: '#e0f0c8',
      bgAlt: '#d0e4b0',
      surface: '#d6e9b8',
      text: '#0f380f',
      muted: '#306230',
      heading: '#0f380f',
      accent: '#306230',
      accentText: '#e0f0c8',
      link: '#1d5c1d',
      border: '#8bac0f',
      codeBg: '#0f380f',
      codeText: '#e0f0c8',
      inlineCodeBg: '#306230',
      inlineCodeText: '#e0f0c8',
      mark: '#9bbc0f',
      markText: '#0f380f',
      selection: '#8bac0f99',
      note: '#0f4a3a',
      tip: '#306230',
      important: '#2f3f6f',
      warning: '#5f4f0f',
      caution: '#6f2f1f',
      syntax: {
        keyword: '#c6f068',
        string: '#9bbc0f',
        number: '#f0f8a0',
        comment: '#7fa05a',
        function: '#e0f0c8',
        type: '#b8d86b',
        variable: '#d4e8b0',
        attr: '#a8d08d',
        tag: '#c6f068',
        punctuation: '#a8c48a',
        meta: '#9bbc0f',
        addition: '#c6f068',
        deletion: '#f2e2a0',
      },
    },
  },
};
