import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Swiss: the International Typographic Style. Grid, heavy rules, huge type, one red. */
export const theme: ThemeDef = {
  id: 'swiss',
  name: 'Swiss',
  tagline: 'International Typographic Style',
  defaultMode: 'light',
  fonts: {
    body: stack('inter', SANS_FALLBACK),
    heading: stack('interTight', SANS_FALLBACK),
    mono: stack('jetbrains', MONO_FALLBACK),
  },
  fontKeys: ['interTight', 'inter', 'jetbrains'],
  baseSize: 17,
  lineHeight: 1.6,
  radius: '0px',
  measure: 760,
  css: () => import('../css/swiss.css?inline').then((m) => m.default),
  card: { background: 'blocks' },
  variants: {
    light: {
      bg: '#ffffff',
      bgAlt: '#f2f2f2',
      surface: '#f7f7f7',
      text: '#111111',
      muted: '#595959',
      heading: '#000000',
      accent: '#e30613',
      accentText: '#ffffff',
      link: '#111111',
      border: '#d0d0d0',
      codeBg: '#f2f2f2',
      codeText: '#111111',
      inlineCodeBg: '#f0f0f0',
      inlineCodeText: '#c20010',
      mark: '#e30613',
      markText: '#ffffff',
      selection: '#e3061333',
      note: '#0047ab',
      tip: '#0b6e2e',
      important: '#6a1b9a',
      warning: '#9a5a00',
      caution: '#c20010',
      syntax: {
        keyword: '#c20010',
        string: '#0b5d1e',
        number: '#0047ab',
        comment: '#6e6e6e',
        function: '#0038a8',
        type: '#7a2e00',
        variable: '#111111',
        attr: '#6a1b9a',
        tag: '#c20010',
        punctuation: '#555555',
        meta: '#595959',
        addition: '#0b5d1e',
        deletion: '#c20010',
      },
    },
    dark: {
      bg: '#0a0a0a',
      bgAlt: '#161616',
      surface: '#121212',
      text: '#f2f2f2',
      muted: '#a6a6a6',
      heading: '#ffffff',
      accent: '#e30613',
      accentText: '#ffffff',
      link: '#ffffff',
      border: '#333333',
      codeBg: '#161616',
      codeText: '#eeeeee',
      inlineCodeBg: '#1c1c1c',
      inlineCodeText: '#ff6b73',
      mark: '#e30613',
      markText: '#ffffff',
      selection: '#e3061366',
      note: '#79a8ff',
      tip: '#7ed491',
      important: '#c79bff',
      warning: '#ffb86b',
      caution: '#ff4d57',
      syntax: {
        keyword: '#ff4d57',
        string: '#7ed491',
        number: '#79a8ff',
        comment: '#8c8c8c',
        function: '#ffffff',
        type: '#ffb86b',
        variable: '#eeeeee',
        attr: '#c79bff',
        tag: '#ff4d57',
        punctuation: '#b0b0b0',
        meta: '#a6a6a6',
        addition: '#7ed491',
        deletion: '#ff4d57',
      },
    },
  },
};
