import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, stack } from '../fonts';

/** Synthwave: outrun neon, a striped sunset and an endless perspective grid. */
export const theme: ThemeDef = {
  id: 'synthwave',
  name: 'Synthwave',
  tagline: 'Neon nights on an endless grid',
  defaultMode: 'dark',
  fonts: {
    body: stack('exo2', SANS_FALLBACK),
    heading: stack('orbitron', SANS_FALLBACK),
    mono: stack('firaCode', MONO_FALLBACK),
  },
  fontKeys: ['orbitron', 'exo2', 'firaCode'],
  baseSize: 17,
  lineHeight: 1.72,
  radius: '8px',
  measure: 840,
  css: () => import('../css/synthwave.css?inline').then((m) => m.default),
  card: { background: 'sun', titleCase: 'upper' },
  variants: {
    dark: {
      bg: '#140a2e',
      bgAlt: '#1c0f3d',
      surface: '#1f1143',
      text: '#f1e9ff',
      muted: '#b9a6e6',
      heading: '#fff0fa',
      accent: '#ff2e97',
      accentText: '#140a2e',
      link: '#2de2e6',
      border: '#3d2a7a',
      codeBg: '#0d0620',
      codeText: '#f1e9ff',
      inlineCodeBg: '#2a1454',
      inlineCodeText: '#ff9de2',
      mark: '#fede5d',
      markText: '#140a2e',
      selection: '#ff2e9766',
      note: '#2de2e6',
      tip: '#72f1b8',
      important: '#c792ff',
      warning: '#fede5d',
      caution: '#ff5c8a',
      syntax: {
        keyword: '#ff2e97',
        string: '#fede5d',
        number: '#f97e72',
        comment: '#8a78c2',
        function: '#2de2e6',
        type: '#fe9e4d',
        variable: '#ff7edb',
        attr: '#fede5d',
        tag: '#72f1b8',
        punctuation: '#c9b8f0',
        meta: '#36f9f6',
        addition: '#72f1b8',
        deletion: '#fe4450',
      },
    },
  },
};
