import type { ThemeDef } from '../types';
import { MONO_FALLBACK, stack } from '../fonts';

/** Terminal: a green-phosphor CRT with scanlines, prompts and a blinking cursor. */
export const theme: ThemeDef = {
  id: 'terminal',
  name: 'Terminal',
  tagline: 'Phosphor green on a humming CRT',
  defaultMode: 'dark',
  fonts: {
    body: stack('plexMono', MONO_FALLBACK),
    heading: stack('vt323', MONO_FALLBACK),
    mono: stack('plexMono', MONO_FALLBACK),
  },
  fontKeys: ['vt323', 'plexMono'],
  baseSize: 15,
  lineHeight: 1.75,
  radius: '0px',
  measure: 840,
  css: () => import('../css/terminal.css?inline').then((m) => m.default),
  card: { background: 'scanlines' },
  variants: {
    dark: {
      bg: '#050a06',
      bgAlt: '#0a140c',
      surface: '#0c1a0f',
      text: '#b6f7c1',
      muted: '#6fae7c',
      heading: '#a4ffb3',
      accent: '#33ff66',
      accentText: '#03140a',
      link: '#5ee0ff',
      border: '#1f4a2a',
      codeBg: '#020603',
      codeText: '#b6f7c1',
      inlineCodeBg: '#0f2214',
      inlineCodeText: '#ffc861',
      mark: '#33ff66',
      markText: '#03140a',
      selection: '#33ff6650',
      note: '#5ee0ff',
      tip: '#7dff95',
      important: '#d49bff',
      warning: '#ffc861',
      caution: '#ff7a7a',
      syntax: {
        keyword: '#ffb454',
        string: '#9dff8a',
        number: '#ffd479',
        comment: '#5a8f65',
        function: '#5ee0ff',
        type: '#7ef0d0',
        variable: '#b6f7c1',
        attr: '#ffd479',
        tag: '#5ee0ff',
        punctuation: '#8fcf9a',
        meta: '#ff8fd8',
        addition: '#7dff95',
        deletion: '#ff7a7a',
      },
    },
  },
};
