import type { ThemeDef } from '../types';
import { MONO_FALLBACK, SANS_FALLBACK, SERIF_FALLBACK, stack } from '../fonts';

/** Zen: washi paper, falling sakura and a great deal of quiet air. */
export const theme: ThemeDef = {
  id: 'zen',
  name: 'Zen Garden',
  tagline: 'Sakura, washi paper and still air',
  defaultMode: 'light',
  fonts: {
    body: stack('zenMaru', SANS_FALLBACK),
    heading: stack('shippori', SERIF_FALLBACK, 'serif'),
    mono: stack('plexMono', MONO_FALLBACK),
  },
  fontKeys: ['zenMaru', 'shippori', 'plexMono'],
  baseSize: 17,
  lineHeight: 1.9,
  radius: '14px',
  measure: 700,
  css: () => import('../css/zen.css?inline').then((m) => m.default),
  card: { background: 'petals' },
  variants: {
    light: {
      bg: '#faf6ef',
      bgAlt: '#f3ece0',
      surface: '#fffdf8',
      text: '#3a3531',
      muted: '#6b645c',
      heading: '#2b2623',
      accent: '#c04c70',
      accentText: '#ffffff',
      link: '#b3436a',
      border: '#e5dacb',
      codeBg: '#f4eee4',
      codeText: '#3a3531',
      inlineCodeBg: '#f6e5ea',
      inlineCodeText: '#98334f',
      mark: '#f8dfe7',
      markText: '#3a3531',
      selection: '#f2c4d299',
      note: '#3d6594',
      tip: '#436b47',
      important: '#78509a',
      warning: '#8f5a1c',
      caution: '#b0384a',
      syntax: {
        keyword: '#a8385f',
        string: '#3f6b44',
        number: '#935420',
        comment: '#857c72',
        function: '#36618a',
        type: '#72509a',
        variable: '#3a3531',
        attr: '#8a5327',
        tag: '#a8385f',
        punctuation: '#665e56',
        meta: '#4b6f60',
        addition: '#3f6b44',
        deletion: '#aa3444',
      },
    },
    dark: {
      bg: '#14161f',
      bgAlt: '#1b1e2a',
      surface: '#1e2130',
      text: '#e7e2dc',
      muted: '#aaa4a8',
      heading: '#f5efe8',
      accent: '#f0a6bd',
      accentText: '#14161f',
      link: '#f4b1c5',
      border: '#2f3344',
      codeBg: '#10121a',
      codeText: '#e1dcd6',
      inlineCodeBg: '#272b3c',
      inlineCodeText: '#f6bccd',
      mark: '#4c2f3e',
      markText: '#fbeff3',
      selection: '#f0a6bd44',
      note: '#a3c6ea',
      tip: '#a9d6b1',
      important: '#d3b8f2',
      warning: '#f0c592',
      caution: '#f6a0ab',
      syntax: {
        keyword: '#f0a6bd',
        string: '#a9d6b1',
        number: '#f2c28f',
        comment: '#7f8599',
        function: '#a0c4e8',
        type: '#d3b8f2',
        variable: '#e1dcd6',
        attr: '#e8caa2',
        tag: '#f0a6bd',
        punctuation: '#b8b2b5',
        meta: '#a9d6c9',
        addition: '#a9d6b1',
        deletion: '#f6a0ab',
      },
    },
  },
};
