import type { SyntaxTokens } from './types';

export interface CodeTheme {
  id: string;
  name: string;
  dark: boolean;
  bg: string;
  text: string;
  syntax: SyntaxTokens;
}

/** Code palettes that can replace a theme's own code colours ("Code theme" setting). */
export const CODE_THEMES: CodeTheme[] = [
  {
    id: 'github-light',
    name: 'GitHub Light',
    dark: false,
    bg: '#f6f8fa',
    text: '#1f2328',
    syntax: {
      keyword: '#cf222e',
      string: '#0a3069',
      number: '#0550ae',
      comment: '#57606a',
      function: '#6639ba',
      type: '#953800',
      variable: '#953800',
      attr: '#0550ae',
      tag: '#116329',
      punctuation: '#1f2328',
      meta: '#0550ae',
      addition: '#116329',
      deletion: '#82071e',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    dark: true,
    bg: '#161b22',
    text: '#e6edf3',
    syntax: {
      keyword: '#ff7b72',
      string: '#a5d6ff',
      number: '#79c0ff',
      comment: '#8b949e',
      function: '#d2a8ff',
      type: '#ffa657',
      variable: '#ffa657',
      attr: '#79c0ff',
      tag: '#7ee787',
      punctuation: '#e6edf3',
      meta: '#79c0ff',
      addition: '#aff5b4',
      deletion: '#ffdcd7',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    dark: true,
    bg: '#282a36',
    text: '#f8f8f2',
    syntax: {
      keyword: '#ff79c6',
      string: '#f1fa8c',
      number: '#bd93f9',
      comment: '#9aa5ce',
      function: '#50fa7b',
      type: '#8be9fd',
      variable: '#ffb86c',
      attr: '#50fa7b',
      tag: '#ff79c6',
      punctuation: '#f8f8f2',
      meta: '#ffb86c',
      addition: '#50fa7b',
      deletion: '#ff5555',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    dark: true,
    bg: '#2e3440',
    text: '#eceff4',
    syntax: {
      keyword: '#81a1c1',
      string: '#a3be8c',
      number: '#c3a1c0',
      comment: '#9aa5b8',
      function: '#88c0d0',
      type: '#8fbcbb',
      variable: '#d8dee9',
      attr: '#8fbcbb',
      tag: '#81a1c1',
      punctuation: '#eceff4',
      meta: '#ebcb8b',
      addition: '#a3be8c',
      deletion: '#e38b92',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    dark: true,
    bg: '#282c34',
    text: '#dcdfe4',
    syntax: {
      keyword: '#c678dd',
      string: '#98c379',
      number: '#d19a66',
      comment: '#8b929e',
      function: '#61afef',
      type: '#e5c07b',
      variable: '#e8838b',
      attr: '#d19a66',
      tag: '#e8838b',
      punctuation: '#dcdfe4',
      meta: '#56b6c2',
      addition: '#98c379',
      deletion: '#e8838b',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    dark: false,
    bg: '#fdf6e3',
    text: '#3c4f56',
    syntax: {
      keyword: '#5f6b00',
      string: '#1f7b74',
      number: '#b3238a',
      comment: '#6c7c80',
      function: '#1f6fae',
      type: '#9a5f00',
      variable: '#1f6fae',
      attr: '#9a5f00',
      tag: '#1f6fae',
      punctuation: '#3c4f56',
      meta: '#c1361f',
      addition: '#5e6b00',
      deletion: '#c42b27',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    dark: true,
    bg: '#272822',
    text: '#f8f8f2',
    syntax: {
      keyword: '#ff5c8f',
      string: '#e6db74',
      number: '#ae81ff',
      comment: '#a39e86',
      function: '#a6e22e',
      type: '#66d9ef',
      variable: '#fd971f',
      attr: '#a6e22e',
      tag: '#ff5c8f',
      punctuation: '#f8f8f2',
      meta: '#66d9ef',
      addition: '#a6e22e',
      deletion: '#ff5c8f',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    dark: true,
    bg: '#011627',
    text: '#d6deeb',
    syntax: {
      keyword: '#c792ea',
      string: '#ecc48d',
      number: '#f78c6c',
      comment: '#8a9fb1',
      function: '#82aaff',
      type: '#ffcb8b',
      variable: '#addb67',
      attr: '#addb67',
      tag: '#7fdbca',
      punctuation: '#d6deeb',
      meta: '#7fdbca',
      addition: '#addb67',
      deletion: '#ef5350',
    },
  },
];

export function getCodeTheme(id: string): CodeTheme | undefined {
  return CODE_THEMES.find((t) => t.id === id);
}
